### ISSUE TITLE
VVM: whitespace in String by print

### ISSUE THREAD

**Issue by benjamin-albrecht** [MastersOfDesaster/VongPiler#42]
Registers: [0 -> 1.0, 1 -> 1.0, 2 -> 2.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
address: 0 -> zal: 1.0Executed command: PRT
Stack: []
Registers: [0 -> 1.0, 1 -> 1.0, 2 -> 2.0, 3 -> yup]
Read raw command: 3  Test
Decoded command to: PSW
Executed command: PSW
Exception in thread "main" java.lang.NullPointerException
        at vong.piler.her.vongruntime.virtualmachine.model.StackElement.toString(StackElement.java:43)
        at java.base/java.lang.String.valueOf(Unknown Source)
        at java.base/java.lang.StringBuilder.append(Unknown Source)
        at java.base/java.util.AbstractCollection.toString(Unknown Source)
        at java.base/java.util.Vector.toString(Unknown Source)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.executeCommand(Steakmachine.java:271)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.run(Steakmachine.java:133)
        at vong.piler.her.vongruntime.main.VongRuntime.main(VongRuntime.java:44)

**Comment by slechte** [comment]
This is a design issue. By design commands are split by whitespace in the binary-file. So it is currently not possible to add whitespace characters to words

**Comment by fspiekermann** [comment]
Close by Pull request #44
