### ISSUE TITLE
VVM Error with more than one input

### ISSUE THREAD

**Issue by benjamin-albrecht** [MastersOfDesaster/Vongpiler#61]
source code:
```2k18
i bims 1 zal max goenn dir 0!!!

i bims 1 zal zaehl goenn dir 0!!!

i bims 1 isso ende goenn dir nope!!!

gieb "gieb anz fibonacci"!!! 

max goenn dir 1gabe!!!

zaehl goenn dir 1gabe!!!
```

Debug output:
```shell
Registers: [0 -> zal: 0.0, 1 -> zal: 1.0, 2 -> zal: 0.0, 3 -> zal: 0.0, 4 -> zal: 0.0, 5 -> isso: nope]
Read raw command: 0 3
Decoded command to: PSA 3
Executed command: PSA
Stack: [address: 3]
Registers: [0 -> zal: 0.0, 1 -> zal: 1.0, 2 -> zal: 0.0, 3 -> zal: 0.0, 4 -> zal: 0.0, 5 -> isso: nope]
Read raw command: 24
Decoded command to: ZIN
10
Executed command: ZIN
Stack: []
Registers: [0 -> zal: 0.0, 1 -> zal: 1.0, 2 -> zal: 0.0, 3 -> zal: 10.0, 4 -> zal: 0.0, 5 -> isso: nope]
Read raw command: 0 4
Decoded command to: PSA 4
Executed command: PSA
Stack: [address: 4]
Registers: [0 -> zal: 0.0, 1 -> zal: 1.0, 2 -> zal: 0.0, 3 -> zal: 10.0, 4 -> zal: 0.0, 5 -> isso: nope]
Read raw command: 24
Decoded command to: ZIN
Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.Scanner.throwFor(Unknown Source)
        at java.base/java.util.Scanner.next(Unknown Source)
        at java.base/java.util.Scanner.nextDouble(Unknown Source)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.readZal(Steakmachine.java:311)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.zin(Steakmachine.java:298)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.executeCommand(Steakmachine.java:284)
        at vong.piler.her.vongruntime.virtualmachine.Steakmachine.run(Steakmachine.java:136)
        at vong.piler.her.vongruntime.main.VongRuntime.main(VongRuntime.java:44)
```

**Comment by slechte** [comment]
PR to fix this issue is open #63
