### ISSUE TITLE
Empty Strings in word don't work

### ISSUE THREAD

**Issue by slechte** [MastersOfDesaster/Vongpiler#65]
The code doesn't compile when I assign an empty String to a word variable.
Example:
```
was ist das fuer 1 code?

i bims 1 word name goenn dir ""!!!

1 nicer!!!
```

Error:
```
Halo I bims 1 Ausname:
java.lang.NullPointerException
	at vong.piler.her.generator.Generator.variableDeclaration(Generator.java:116)
	at vong.piler.her.generator.Generator.generate(Generator.java:38)
	at vong.piler.her.Main.main(Main.java:68)
```

**Comment by slechte** [comment]
Fixed by #66
